# https://config.travis-ci.com/explore

language: c
dist: bionic

# Use full depth for SonarCloud
git:
  depth: false

addons:
  sonarcloud:
    organization: "corentinmusard"
    token:
      secure: "wBY+yjVkmiXr02DLt+we8Zsm33pSSUyP7eSXmrq6/A71euU1FOWwajDclJM3slH3deebxw8QH16PeBKKhL2UF9E5y5d9H5VeHIa1eqvwMos7lOlom3FI0C3ESJOYz92uMqzhm3LNcWE4+fOR55itTjPeMfAzPZRaJgDRJFdfiSAOJkRsv0ZOH61Aayn7kc7mU5g9SmuePWawYf2DeDmD1IRNG3WLHJfhWy6aqrhvsexdOJzyorRkKeHh/3+WiUTXSvyQ9HGrmwZ5zfh4/+rUddJ/0p3hqNVA8FRsuGIf4AO+dznDYZOmgZPT8kGE3NuoxHuH8wF7JQd0O8WdfDAKDqhvd0KIKJE9ZulycvZGd9a1ehin+VNwEKIHI7n56EfazyqFaXlXl8tyEGjyVkrnZV1Tm39wgPk+bFBR08Bw49/l4dF+kPubjVnnHc2ij/1+Qt3NeCeqCRhA8kp6KvcxPnyl5iYoqbh+O79jj9qwzL3vQ5JEEALnHGvPtsKAymeX7EfHa2IykQiVGpxsMuqIMrriCHlCZ5t004Xy+vfG5zLSUgLCJIBwCJhn2xRUtFvHbpfYVQBYunQ5yYHb6dNlMNA4T/I3ABgpnCUxTpOfP+n0WImnSU6dLNyMCGP5G77q6qKcDcUypg77tZAZSatWfKBJxH7r5n6aAgpEKSCvJo0="
  apt:
    packages: # Install needed packages
      - gcc-8
      - g++-8
      - clang-6.0
      - clang++-6.0

os:
  - linux

# To build each config
jobs:
  include:
    - name: "Linux gcc8, gcov8"
      env:
        - CC=gcc-8
        - CXX=g++-8
        - GCOV=true

    - name: "Linux clang6"
      env:
        - CC=clang-6.0
        - CXX=clang++-6.0

# command to build and run tests
script:
  - mkdir build
  - cd build
  - cmake ../
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir ../bw-output make all

  # Execute some tests
  - GTEST_COLOR=1 ctest --verbose

  # Execute gcov for tests coverage
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - |
    if [[ $GCOV ]]; then
      gcov-8 -b $(find ./tests/ -name "*.o");
      bash <(curl -s https://codecov.io/bash);
      cd ../;
      sonar-scanner;
    fi
